# Generated by Django 4.2.4 on 2023-08-21 16:26

import announcement.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Started')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Ended')),
                ('template_document', models.FileField(blank=True, null=True, upload_to=announcement.models.class_folder)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
