# Generated by Django 4.2.4 on 2023-09-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Час закінчення подачі'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Закінчення'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Початок'),
        ),
    ]
