# Generated by Django 4.2.4 on 2023-08-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
